language: node_js
cache: yarn
node_js:
  - '8.11.1'
services:
  - docker
install:
  - npm i -g rimraf
  - npm i -g cross-env
  - yarn bootstrap
  - yarn configure
matrix:
  include:
    - env: SUITE=2017
    - env: SUITE=2018
    - env: SUITE=COMPONENT_LIBRARY
script:
  - yarn travis
after_success:
  - make deploy
