language: node_js
cache: yarn
node_js:
  - '6.11.4'
install:
  - npm i -g npx
  - yarn
  - yarn bootstrap
  - yarn build
matrix:
  include:
    - env: SUITE=2017
    - env: SUITE=COMPONENT_LIBRARY
script:
  - yarn run travis
