language: node_js
cache: yarn
node_js:
  - '10.15.3'
services:
  - docker
install:
  - npm i -g npx
  - npm i -g rimraf
  - npm i -g cross-env
  - yarn bootstrap
  - yarn run configure
matrix:
  include:
    - env: SUITE=2017
    - env: SUITE=2018
    - env: SUITE=COMPONENT_LIBRARY
script:
  - yarn run travis
after_success:
  - make deploy
